In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pytesseract
import cv2
from pytesseract import Output

In [15]:
custom_config = r'--oem 3 --psm 6'
image = '/home/vimalkumar/Documents/images/Interview/image_1.jpg'
text_data = pytesseract.image_to_data(image,config=custom_config,
                                          output_type=Output.DICT)

In [16]:
text_data_1 = pytesseract.image_to_string(image,config=custom_config)
print(text_data_1)

Page 1 of 1
Bill-to Customer No.
Prices Including VAT No
Document Date 14. December 2020
Salesperson Niall Gannon
Your Order No. Pe
Job Location
Cheque No.
Our Order No. |
Payment Method ON A/C TRA
Goods Collected By
Delivery Instructions:
Unit of VAT
No. Description Qty Measure Unit Price Discount % Identifier Amount
FO27103 FIBERGLASS LADDER 3 STEP 3 EACH 35.00 HIGHC 105.00
FO27104 FIBERGLASS LADDER 4 STEP 3. EACH 41.50 HIGHC 124.50
FO27105 FIBERGLASS LADDER 5 STEP 3 EACH 47.00 HIGHC 141.00
FO27106 FIBERGLASS LADDER 6 STEP 3 EACH 55.00 HIGHC 165.00
LFD66AL ALUMINIUM 2 STEP STOOL 3 EACH 16.00 HIGHC 48.00
LAD430GFA FIBERGLASS EXT LADDER 28STEP 7.6MTR 1 EACH 125.00 HIGHC 125.00
LADS60GFA FIBERGLASS EXT LADDER 36STEP 9.7MTR 1 EACH 150.00 HIGHC 150.00
Total EUR Excl. VAT 858.50
21% VAT 180.29
Total EUR Incl. VAT 1,038.79
Goods remain strictly the property of the Vendor until paid in full

In [17]:
df = pd.DataFrame(text_data)
df

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text
0,1,1,0,0,0,0,0,0,1654,2339,-1,
1,2,1,1,0,0,0,97,146,1448,2080,-1,
2,3,1,1,1,0,0,109,146,1436,2080,-1,
3,4,1,1,1,1,0,1433,146,108,22,-1,
4,5,1,1,1,1,1,1433,146,49,22,95,Page
...,...,...,...,...,...,...,...,...,...,...,...,...
174,5,1,1,1,25,8,891,2200,89,21,96,Vendor
175,5,1,1,1,25,9,989,2200,47,21,94,until
176,5,1,1,1,25,10,1047,2200,50,26,96,paid
177,5,1,1,1,25,11,1108,2200,18,20,95,in
178,5,1,1,1,25,12,1136,2200,33,21,95,full

In [18]:
df = df.drop(["level","page_num","par_num","block_num","conf",
                  "width","height"],axis = 1)
df

     line_num  word_num  left   top    text
0           0         0     0     0
1           0         0    97   146
2           0         0   109   146
3           1         0  1433   146
4           1         1  1433   146    Page
..        ...       ...   ...   ...     ...
174        25         8   891  2200  Vendor
175        25         9   989  2200   until
176        25        10  1047  2200    paid
177        25        11  1108  2200      in
178        25        12  1136  2200    full

[179 rows x 5 columns]

In [19]:
pd.set_option('display.max_rows',1000)

In [20]:
df

     line_num  word_num  left   top           text
0           0         0     0     0
1           0         0    97   146
2           0         0   109   146
3           1         0  1433   146
4           1         1  1433   146           Page
5           1         2  1492   147              1
6           1         3  1509   146             of
7           1         4  1535   147              1
8           2         0  1036   416
9           2         1  1036   416        Bill-to
10          2         2  1099   417       Customer
11          2         3  1201   417            No.
12          3         0  1036   454
13          3         1  1036   454         Prices
14          3         2  1099   454      Including
15          3         3  1194   455            VAT
16          3         4  1451   455             No
17          4         0  1036   492
18          4         1  1036   493       Document
19          4         2  1144   493           Date
20          4         3  1292   492            14.
21          4         4  1326   492       December
22          4         5  1432   492           2020
23          5         0  1035   526
24          5         1  1035   526    Salesperson
25          5         2  1353   530          Niall
26          5         3  1402   530         Gannon
27          6         0  1035   544
28          6         1  1035   568           Your
29          6         2  1086   567          Order
30          6         3  1150   568            No.
31          6         4  1255   544             Pe
32          7         0  1034   605
33          7         1  1034   605            Job
34          7         2  1076   605       Location
35          8         0  1035   643
36          8         1  1035   643         Cheque
37          8         2  1117   644            No.
38          9         0  1035   652
39          9         1  1035   681            Our
40          9         2  1078   681          Order
41          9         3  1142   682            No.
42          9         4  1329   652              |
43         10         0  1036   715
44         10         1  1036   720        Payment
45         10         2  1127   719         Method
46         10         3  1352   715             ON
47         10         4  1392   715            A/C
48         10         5  1435   715            TRA
49         11         0  1035   756
50         11         1  1035   756          Goods
51         11         2  1105   756      Collected
52         11         3  1203   757             By
53         12         0   109   842
54         12         1   109   842       Delivery
55         12         2   193   842  Instructions:
56         13         0   884   978
57         13         1   884   979           Unit
58         13         2   933   978             of
59         13         3  1310   979            VAT
60         14         0   116  1004
61         14         1   116  1004            No.
62         14         2   308  1004    Description
63         14         3   817  1009            Qty
64         14         4   884  1009        Measure
65         14         5  1032  1009           Unit
66         14         6  1083  1009          Price
67         14         7  1166  1009       Discount
68         14         8  1263  1009              %
69         14         9  1311  1008     Identifier
70         14        10  1460  1009         Amount
71         15         0   111  1062
72         15         1   111  1062        FO27103
73         15         2   317  1066     FIBERGLASS
74         15         3   441  1067         LADDER
75         15         4   527  1066              3
76         15         5   545  1066           STEP
77         15         6   832  1066              3
78         15         7   884  1066           EACH
79         15         8  1081  1062          35.00
80         15         9  1312  1066          HIGHC
81         15        10  1483  1066         105.00
82         16         0   111  1092
83         16         1   111  1096        FO27104
84         16         2   317  1096     FIBERGLASS
85         16         3   441  1096         LADDER
86         16         4   526  1096              4
87         16         5   545  1096           STEP
88         16         6   823  1092             3.
89         16         7   884  1096           EACH
90         16         8  1080  1092          41.50
91         16         9  1312  1096          HIGHC
92         16        10  1483  1096         124.50
93         17         0   111  1122
94         17         1   111  1126        FO27105
95         17         2   317  1126     FIBERGLASS
96         17         3   441  1126         LADDER
97         17         4   527  1126              5
98         17         5   545  1126           STEP
99         17         6   832  1126              3
100        17         7   884  1126           EACH
101        17         8  1080  1122          47.00
102        17         9  1312  1126          HIGHC
103        17        10  1483  1126         141.00
104        18         0   111  1151
105        18         1   111  1155        FO27106
106        18         2   317  1155     FIBERGLASS
107        18         3   441  1156         LADDER
108        18         4   527  1155              6
109        18         5   545  1155           STEP
110        18         6   832  1155              3
111        18         7   884  1155           EACH
112        18         8  1082  1151          55.00
113        18         9  1312  1155          HIGHC
114        18        10  1483  1155         165.00
115        19         0   111  1181
116        19         1   111  1185        LFD66AL
117        19         2   316  1185      ALUMINIUM
118        19         3   446  1185              2
119        19         4   464  1185           STEP
120        19         5   517  1185          STOOL
121        19         6   832  1185              3
122        19         7   884  1185           EACH
123        19         8  1082  1181          16.00
124        19         9  1312  1185          HIGHC
125        19        10  1493  1185          48.00
126        20         0    97  1210
127        20         1    97  1210      LAD430GFA
128        20         2   317  1214     FIBERGLASS
129        20         3   441  1215            EXT
130        20         4   483  1215         LADDER
131        20         5   569  1214         28STEP
132        20         6   645  1214         7.6MTR
133        20         7   833  1214              1
134        20         8   884  1214           EACH
135        20         9  1070  1210         125.00
136        20        10  1312  1214          HIGHC
137        20        11  1483  1214         125.00
138        21         0    97  1240
139        21         1    97  1240      LADS60GFA
140        21         2   317  1244     FIBERGLASS
141        21         3   441  1244            EXT
142        21         4   483  1244         LADDER
143        21         5   569  1244         36STEP
144        21         6   645  1244         9.7MTR
145        21         7   833  1244              1
146        21         8   884  1244           EACH
147        21         9  1070  1240         150.00
148        21        10  1312  1244          HIGHC
149        21        11  1483  1244         150.00
150        22         0  1170  1329
151        22         1  1170  1329          Total
152        22         2  1231  1329            EUR
153        22         3  1279  1329          Excl.
154        22         4  1331  1329            VAT
155        22         5  1476  1329         858.50
156        23         0  1287  1359
157        23         1  1287  1359            21%
158        23         2  1335  1359            VAT
159        23         3  1483  1359         180.29
160        24         0  1173  1416
161        24         1  1173  1416          Total
162        24         2  1234  1416            EUR
163        24         3  1283  1416          Incl.
164        24         4  1331  1416            VAT
165        24         5  1459  1416       1,038.79
166        25         0   390  2199
167        25         1   390  2199          Goods
168        25         2   480  2200         remain
169        25         3   571  2200       strictly
170        25         4   657  2200            the
171        25         5   704  2201       property
172        25         6   814  2200             of
173        25         7   844  2200            the
174        25         8   891  2200         Vendor
175        25         9   989  2200          until
176        25        10  1047  2200           paid
177        25        11  1108  2200             in
178        25        12  1136  2200           full

In [25]:
Quantity=[]
for idx,word in enumerate(df["text"]):
        if word.lower() == "Qty".lower() or word.lower() == "Quantity".lower():
             #print(word)
             line_no_1 = df["line_num"][idx]
             new_df = df[idx:]
             #print(new_df)
             new_df.reset_index(drop=True, inplace=True)
             position = df["left"][idx]
             #print(position)
             #text = new_df[ new_df["word_num"] == word_no]
             # Extract quantity of each line items
             for t,(txt, j) in enumerate(zip(new_df["text"],new_df["left"])):
                #print(txt)
                #print(j)
                if (abs(j-position) < 100) :
                     
                    if txt.isnumeric() == True:
                        top_1 = new_df["top"][t]
                         
                        Quantity.append((txt))

In [26]:
Quantity

['3', '3', '3', '3', '1', '1']

In [30]:
for idx,word in enumerate(df["text"]):
    if word.lower() == "Qty".lower() or word.lower() == "Quantity".lower():
        print(word)
        print(idx)
        line_no_1 = df["line_num"][idx]
        print(line_no_1)
        word_no_1 = df["word_num"][idx]
        print(word_no_1)

Qty
63
14
3

In [28]:
for i in range(1,len(df)):
    df1 = df[(df.line_num == line_no_1 + i) & (df.word_num == word_no_1)]
    #print(df1)
    for x in df1['text']:
        #print(x)
        if x.isnumeric():
            print(x)
        else:
            break

2

In [44]:
Quantity=[]
for idx,word in enumerate(df["text"]):
        if word.lower() == "Qty".lower() or word.lower() == "Quantity".lower():
             line_no_1 = df["line_num"][idx]
             new_df = df[idx:]
             #print(new_df)
             new_df.reset_index(drop=True, inplace=True)
             position = df["left"][idx]
             #text = new_df[ new_df["word_num"] == word_no]
             # Extract quantity of each line items
             for t,(txt, j) in enumerate(zip(new_df["text"],new_df["left"])):
                 if (abs(j-position) < 50) :
                     
                     if txt.isnumeric() == True:
                         #top_1 = new_df["top"][t]
                         
                         Quantity.append(int(txt))

In [45]:
Quantity

[4, 1]

In [43]:
new_df["line_num"][6]

17

In [41]:
vat_price = []
for i,(txt, k) in enumerate(zip(new_df["text"],new_df["left"])):
                 if txt.lower() == "VAT".lower():
                     line_no_2 = new_df["line_num"][i]
                     print(line_no_2)
                     
                     if line_no_1 == line_no_2:
                         vat = []
                         position_1 = new_df["left"][i]
                         for j,(txt, k) in enumerate(zip(new_df["text"],new_df["left"])):
                             if (abs(k-position_1) < 50) :
                                 top = new_df["top"][j]
                                
                                 if top <= (top_1+10):
                                     if (txt.replace('.', '', 1).isdigit()) == True:
                                      vat.append(txt)
                                      
                         vat_price.append(vat)

17
17
25

In [ ]:
(df['line_num']== line_no_1 + 1) and (df['word_num'] == 1)

In [ ]:
df1 = df[(df.line_num == 18) & (df.word_num == 1)]
df1

In [ ]:
for i in df1['text']:
    print(i)

In [4]:
import pytesseract
from pytesseract import Output

In [5]:
custom_config = r'--oem 3 --psm 6'
image = '/home/vimalkumar/Documents/images/Interview/image_1.jpg'
text_data = pytesseract.image_to_boxes(image,config=custom_config,
                                          output_type=Output.DICT)

In [35]:
print(text_data)

{'char': ['P', 'a', 'g', 'e', '1', 'o', 'f', '1', 'B', 'i', 'l', 'l', '-', 't', 'o', 'C', 'u', 's', 't', 'o', 'm', 'e', 'r', 'N', 'o', '.', 'P', 'r', 'i', 'c', 'e', 's', 'I', 'n', 'c', 'l', 'u', 'd', 'i', 'n', 'g', 'V', 'A', 'T', 'N', 'o', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 'D', 'a', 't', 'e', '1', '4', '.', 'D', 'e', 'c', 'e', 'm', 'b', 'e', 'r', '2', '0', '2', '0', 'S', 'a', 'l', 'e', 's', 'p', 'e', 'r', 's', 'o', 'n', 'N', 'i', 'a', 'l', 'l', 'G', 'a', 'n', 'n', 'o', 'n', 'Y', 'o', 'u', 'r', 'O', 'r', 'd', 'e', 'r', 'N', 'o', '.', 'P', 'e', 'J', 'o', 'b', 'L', 'o', 'c', 'a', 't', 'i', 'o', 'n', 'C', 'h', 'e', 'q', 'u', 'e', 'N', 'o', '.', 'O', 'u', 'r', 'O', 'r', 'd', 'e', 'r', 'N', 'o', '.', '|', 'P', 'a', 'y', 'm', 'e', 'n', 't', 'M', 'e', 't', 'h', 'o', 'd', 'O', 'N', 'A', '/', 'C', 'T', 'R', 'A', 'G', 'o', 'o', 'd', 's', 'C', 'o', 'l', 'l', 'e', 'c', 't', 'e', 'd', 'B', 'y', 'D', 'e', 'l', 'i', 'v', 'e', 'r', 'y', 'I', 'n', 's', 't', 'r', 'u', 'c', 't', 'i', 'o', 'n', 's', ':', 'U', 'n', 'i', 't', 'o', 'f', 'V', 'A', 'T', 'N', 'o', '.', 'D', 'e', 's', 'c', 'r', 'i', 'p', 't', 'i', 'o', 'n', 'Q', 't', 'y', 'M', 'e', 'a', 's', 'u', 'r', 'e', 'U', 'n', 'i', 't', 'P', 'r', 'i', 'c', 'e', 'D', 'i', 's', 'c', 'o', 'u', 'n', 't', '%', 'I', 'd', 'e', 'n', 't', 'i', 'f', 'i', 'e', 'r', 'A', 'm', 'o', 'u', 'n', 't', 'F', 'O', '2', '7', '1', '0', '3', 'F', 'I', 'B', 'E', 'R', 'G', 'L', 'A', 'S', 'S', 'L', 'A', 'D', 'D', 'E', 'R', '3', 'S', 'T', 'E', 'P', '3', 'E', 'A', 'C', 'H', '3', '5', '.', '0', '0', 'H', 'I', 'G', 'H', 'C', '1', '0', '5', '.', '0', '0', 'F', 'O', '2', '7', '1', '0', '4', 'F', 'I', 'B', 'E', 'R', 'G', 'L', 'A', 'S', 'S', 'L', 'A', 'D', 'D', 'E', 'R', '4', 'S', 'T', 'E', 'P', '3', '.', 'E', 'A', 'C', 'H', '4', '1', '.', '5', '0', 'H', 'I', 'G', 'H', 'C', '1', '2', '4', '.', '5', '0', 'F', 'O', '2', '7', '1', '0', '5', 'F', 'I', 'B', 'E', 'R', 'G', 'L', 'A', 'S', 'S', 'L', 'A', 'D', 'D', 'E', 'R', '5', 'S', 'T', 'E', 'P', '3', 'E', 'A', 'C', 'H', '4', '7', '.', '0', '0', 'H', 'I', 'G', 'H', 'C', '1', '4', '1', '.', '0', '0', 'F', 'O', '2', '7', '1', '0', '6', 'F', 'I', 'B', 'E', 'R', 'G', 'L', 'A', 'S', 'S', 'L', 'A', 'D', 'D', 'E', 'R', '6', 'S', 'T', 'E', 'P', '3', 'E', 'A', 'C', 'H', '5', '5', '.', '0', '0', 'H', 'I', 'G', 'H', 'C', '1', '6', '5', '.', '0', '0', 'L', 'F', 'D', '6', '6', 'A', 'L', 'A', 'L', 'U', 'M', 'I', 'N', 'I', 'U', 'M', '2', 'S', 'T', 'E', 'P', 'S', 'T', 'O', 'O', 'L', '3', 'E', 'A', 'C', 'H', '1', '6', '.', '0', '0', 'H', 'I', 'G', 'H', 'C', '4', '8', '.', '0', '0', 'L', 'A', 'D', '4', '3', '0', 'G', 'F', 'A', 'F', 'I', 'B', 'E', 'R', 'G', 'L', 'A', 'S', 'S', 'E', 'X', 'T', 'L', 'A', 'D', 'D', 'E', 'R', '2', '8', 'S', 'T', 'E', 'P', '7', '.', '6', 'M', 'T', 'R', '1', 'E', 'A', 'C', 'H', '1', '2', '5', '.', '0', '0', 'H', 'I', 'G', 'H', 'C', '1', '2', '5', '.', '0', '0', 'L', 'A', 'D', 'S', '6', '0', 'G', 'F', 'A', 'F', 'I', 'B', 'E', 'R', 'G', 'L', 'A', 'S', 'S', 'E', 'X', 'T', 'L', 'A', 'D', 'D', 'E', 'R', '3', '6', 'S', 'T', 'E', 'P', '9', '.', '7', 'M', 'T', 'R', '1', 'E', 'A', 'C', 'H', '1', '5', '0', '.', '0', '0', 'H', 'I', 'G', 'H', 'C', '1', '5', '0', '.', '0', '0', 'T', 'o', 't', 'a', 'l', 'E', 'U', 'R', 'E', 'x', 'c', 'l', '.', 'V', 'A', 'T', '8', '5', '8', '.', '5', '0', '2', '1', '%', 'V', 'A', 'T', '1', '8', '0', '.', '2', '9', 'T', 'o', 't', 'a', 'l', 'E', 'U', 'R', 'I', 'n', 'c', 'l', '.', 'V', 'A', 'T', '1', ',', '0', '3', '8', '.', '7', '9', 'G', 'o', 'o', 'd', 's', 'r', 'e', 'm', 'a', 'i', 'n', 's', 't', 'r', 'i', 'c', 't', 'l', 'y', 't', 'h', 'e', 'p', 'r', 'o', 'p', 'e', 'r', 't', 'y', 'o', 'f', 't', 'h', 'e', 'V', 'e', 'n', 'd', 'o', 'r', 'u', 'n', 't', 'i', 'l', 'p', 'a', 'i', 'd', 'i', 'n', 'f', 'u', 'l', 'l'], 'left': [1433, 1433, 1447, 1460, 1492, 1509, 1521, 1535, 1036, 1036, 1048, 1054, 1064, 1072, 1080, 1099, 1113, 1125, 1134, 1143, 1156, 1161, 1175, 1201, 1205, 1216, 1036, 1036, 1048, 1056, 1071, 1082, 1099, 1104, 1116, 1127, 1132, 1144, 1158, 1163, 1175, 1194, 1208, 1222, 1451, 1467, 1036, 1050, 1063, 1074, 1075, 1087, 1105, 1118, 1144, 1144, 1159, 1169, 1292, 1301, 1314, 1326, 1341, 1352, 1362, 1375, 1380, 1394, 1406, 1432, 1444, 1445, 1456, 1035, 1036, 1047, 1063, 1075, 1085, 1097, 1098, 1110, 1126, 1140, 1353, 1353, 1370, 1374, 1386, 1402, 1418, 1430, 1442, 1444, 1454, 1035, 1036, 1047, 1061, 1086, 1091, 1104, 1111, 1124, 1150, 1153, 1166, 1255, 1329, 1034, 1043, 1056, 1076, 1079, 1085, 1098, 1108, 1119, 1133, 1146, 1035, 1049, 1051, 1061, 1073, 1086, 1117, 1117, 1133, 1035, 1038, 1052, 1078, 1078, 1095, 1103, 1116, 1142, 1144, 1157, 1329, 1036, 1047, 1058, 1060, 1070, 1088, 1101, 1127, 1134, 1146, 1166, 1178, 1191, 1352, 1370, 1392, 1406, 1413, 1435, 1450, 1464, 1035, 1038, 1050, 1063, 1076, 1105, 1105, 1119, 1132, 1137, 1143, 1154, 1171, 1183, 1203, 1214, 109, 109, 123, 135, 141, 145, 156, 168, 193, 199, 211, 220, 220, 228, 240, 248, 258, 271, 277, 285, 297, 884, 884, 900, 913, 933, 933, 1310, 1325, 1340, 116, 125, 141, 308, 317, 332, 344, 354, 365, 380, 393, 403, 409, 423, 817, 820, 833, 884, 884, 904, 916, 928, 938, 952, 1032, 1032, 1048, 1061, 1083, 1096, 1105, 1111, 1122, 1166, 1166, 1182, 1198, 1208, 1222, 1235, 1248, 1263, 1311, 1311, 1318, 1331, 1344, 1356, 1366, 1371, 1387, 1399, 1460, 1466, 1477, 1497, 1511, 1524, 111, 121, 138, 149, 163, 162, 173, 317, 328, 334, 347, 358, 370, 375, 386, 400, 411, 441, 450, 466, 470, 481, 497, 527, 545, 556, 569, 580, 832, 884, 894, 909, 923, 1081, 1082, 1094, 1110, 1122, 1312, 1327, 1332, 1348, 1363, 1483, 1493, 1506, 1518, 1522, 1534, 111, 121, 138, 150, 163, 173, 184, 317, 328, 334, 347, 358, 370, 375, 386, 411, 422, 441, 450, 466, 467, 481, 497, 526, 545, 556, 569, 580, 823, 832, 884, 894, 909, 923, 1080, 1083, 1094, 1110, 1122, 1312, 1327, 1332, 1348, 1363, 1483, 1494, 1495, 1505, 1523, 1534, 111, 121, 138, 149, 163, 173, 186, 317, 328, 334, 347, 358, 370, 375, 386, 411, 422, 441, 450, 466, 467, 481, 497, 527, 545, 556, 569, 580, 832, 884, 894, 909, 923, 1080, 1083, 1093, 1110, 1122, 1312, 1327, 1332, 1348, 1363, 1483, 1493, 1507, 1518, 1522, 1534, 111, 121, 138, 149, 163, 173, 185, 317, 328, 334, 347, 358, 370, 375, 386, 411, 422, 441, 450, 466, 467, 481, 497, 527, 545, 556, 569, 580, 832, 884, 894, 909, 923, 1082, 1083, 1094, 1110, 1122, 1312, 1327, 1332, 1348, 1363, 1483, 1484, 1494, 1518, 1522, 1534, 111, 121, 132, 147, 159, 170, 186, 316, 331, 342, 345, 357, 377, 383, 400, 421, 446, 464, 475, 488, 500, 517, 528, 540, 548, 557, 832, 884, 894, 909, 923, 1082, 1082, 1093, 1110, 1122, 1312, 1327, 1332, 1348, 1363, 1493, 1496, 1505, 1522, 1534, 97, 111, 136, 149, 163, 174, 186, 202, 212, 317, 328, 334, 347, 358, 370, 375, 386, 395, 411, 441, 451, 464, 483, 492, 508, 513, 523, 539, 569, 569, 580, 593, 604, 617, 645, 658, 662, 675, 694, 707, 833, 884, 894, 909, 923, 1070, 1081, 1082, 1094, 1110, 1122, 1312, 1327, 1332, 1348, 1363, 1483, 1494, 1506, 1518, 1522, 1534, 97, 111, 136, 151, 162, 174, 186, 202, 212, 317, 328, 334, 347, 358, 370, 375, 386, 395, 411, 441, 451, 464, 483, 491, 508, 523, 525, 539, 569, 571, 581, 593, 605, 617, 645, 658, 662, 675, 693, 707, 833, 884, 894, 909, 923, 1070, 1082, 1082, 1093, 1110, 1122, 1312, 1327, 1332, 1348, 1363, 1483, 1494, 1495, 1505, 1522, 1534, 1170, 1170, 1183, 1196, 1205, 1231, 1242, 1259, 1279, 1279, 1290, 1303, 1320, 1331, 1346, 1361, 1476, 1489, 1492, 1502, 1521, 1533, 1287, 1301, 1311, 1335, 1349, 1363, 1483, 1493, 1495, 1505, 1522, 1534, 1173, 1173, 1187, 1200, 1209, 1234, 1236, 1246, 1283, 1283, 1289, 1302, 1320, 1331, 1346, 1361, 1459, 1470, 1476, 1489, 1492, 1502, 1515, 1533, 390, 390, 411, 427, 442, 480, 480, 493, 504, 527, 543, 571, 571, 585, 594, 608, 610, 622, 636, 657, 666, 681, 704, 720, 729, 733, 745, 760, 776, 784, 814, 814, 844, 853, 868, 891, 910, 913, 926, 940, 956, 989, 989, 1004, 1018, 1028, 1047, 1050, 1063, 1079, 1108, 1108, 1136, 1136, 1145, 1160], 'bottom': [2171, 2176, 2176, 2171, 2176, 2176, 2176, 2176, 1906, 1906, 1906, 1906, 1912, 1906, 1906, 1906, 1906, 1906, 1906, 1906, 1906, 1906, 1906, 1906, 1906, 1906, 1868, 1868, 1868, 1868, 1868, 1868, 1868, 1868, 1868, 1868, 1868, 1868, 1868, 1868, 1863, 1868, 1868, 1868, 1868, 1868, 1831, 1830, 1830, 1830, 1830, 1831, 1830, 1830, 1830, 1831, 1830, 1830, 1831, 1831, 1830, 1831, 1830, 1830, 1830, 1831, 1830, 1830, 1830, 1831, 1830, 1830, 1830, 1792, 1783, 1792, 1792, 1792, 1787, 1792, 1783, 1792, 1792, 1793, 1792, 1793, 1793, 1792, 1793, 1792, 1792, 1793, 1793, 1792, 1792, 1755, 1755, 1755, 1755, 1755, 1755, 1755, 1755, 1755, 1755, 1755, 1755, 1739, 1743, 1717, 1717, 1717, 1717, 1717, 1717, 1717, 1717, 1717, 1717, 1717, 1679, 1679, 1674, 1679, 1674, 1679, 1679, 1679, 1679, 1641, 1641, 1642, 1641, 1641, 1642, 1642, 1641, 1642, 1642, 1642, 1633, 1604, 1603, 1598, 1598, 1604, 1603, 1603, 1604, 1603, 1603, 1603, 1603, 1603, 1607, 1608, 1607, 1607, 1607, 1608, 1608, 1608, 1566, 1566, 1566, 1566, 1566, 1566, 1566, 1566, 1566, 1566, 1566, 1566, 1566, 1566, 1566, 1561, 1475, 1480, 1480, 1480, 1480, 1480, 1480, 1475, 1480, 1480, 1480, 1480, 1480, 1480, 1480, 1480, 1480, 1480, 1480, 1480, 1480, 1343, 1343, 1344, 1343, 1343, 1343, 1344, 1344, 1344, 1305, 1314, 1314, 1305, 1314, 1314, 1314, 1314, 1314, 1309, 1314, 1314, 1314, 1314, 1312, 1309, 1309, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1314, 1257, 1256, 1257, 1257, 1257, 1247, 1256, 1257, 1257, 1257, 1257, 1257, 1256, 1256, 1257, 1256, 1256, 1257, 1257, 1257, 1257, 1257, 1257, 1256, 1256, 1257, 1257, 1257, 1256, 1257, 1257, 1256, 1257, 1256, 1247, 1256, 1256, 1256, 1257, 1257, 1256, 1257, 1256, 1257, 1256, 1256, 1257, 1256, 1256, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1218, 1227, 1227, 1227, 1227, 1227, 1227, 1218, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1227, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1188, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1197, 1168, 1167, 1168, 1168, 1168, 1167, 1167, 1168, 1168, 1168, 1168, 1168, 1167, 1167, 1168, 1167, 1167, 1168, 1168, 1168, 1168, 1168, 1168, 1167, 1167, 1168, 1168, 1168, 1167, 1168, 1168, 1167, 1168, 1167, 1158, 1167, 1167, 1167, 1168, 1168, 1167, 1168, 1167, 1168, 1167, 1167, 1168, 1167, 1167, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1129, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1138, 1100, 1109, 1109, 1109, 1108, 1108, 1108, 1109, 1109, 1109, 1109, 1109, 1109, 1109, 1108, 1108, 1109, 1108, 1108, 1109, 1109, 1109, 1109, 1109, 1109, 1109, 1109, 1109, 1109, 1108, 1108, 1108, 1109, 1109, 1109, 1109, 1108, 1109, 1109, 1109, 1109, 1109, 1109, 1108, 1109, 1109, 1109, 1100, 1108, 1108, 1108, 1109, 1109, 1108, 1109, 1108, 1109, 1109, 1108, 1109, 1108, 1108, 1070, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1070, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 1079, 993, 994, 993, 993, 994, 994, 993, 994, 993, 994, 994, 993, 994, 994, 994, 994, 994, 993, 993, 993, 993, 994, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 906, 907, 906, 906, 906, 907, 906, 906, 906, 907, 907, 906, 907, 907, 907, 907, 907, 904, 906, 906, 904, 906, 907, 906, 118, 118, 118, 118, 118, 118, 118, 118, 119, 118, 119, 113, 118, 118, 119, 118, 113, 118, 113, 118, 119, 118, 113, 119, 118, 113, 113, 118, 119, 113, 118, 118, 118, 119, 118, 119, 118, 118, 119, 118, 118, 118, 118, 119, 118, 119, 113, 113, 118, 118, 119, 119, 118, 119, 118, 119], 'right': [1445, 1445, 1458, 1482, 1497, 1519, 1526, 1541, 1043, 1046, 1050, 1061, 1070, 1079, 1091, 1111, 1123, 1133, 1141, 1153, 1172, 1182, 1193, 1214, 1226, 1232, 1045, 1046, 1054, 1069, 1081, 1090, 1101, 1114, 1125, 1129, 1142, 1155, 1160, 1173, 1186, 1207, 1221, 1233, 1464, 1478, 1049, 1062, 1072, 1084, 1097, 1103, 1115, 1136, 1154, 1157, 1168, 1187, 1297, 1312, 1317, 1339, 1351, 1361, 1372, 1391, 1401, 1404, 1425, 1442, 1454, 1466, 1478, 1045, 1056, 1061, 1073, 1083, 1095, 1107, 1119, 1124, 1137, 1149, 1364, 1366, 1372, 1383, 1394, 1415, 1427, 1439, 1452, 1464, 1477, 1046, 1056, 1058, 1080, 1101, 1111, 1110, 1121, 1142, 1163, 1174, 1182, 1433, 1494, 1040, 1054, 1067, 1084, 1095, 1096, 1107, 1117, 1130, 1144, 1156, 1047, 1059, 1071, 1071, 1083, 1108, 1126, 1130, 1148, 1050, 1058, 1071, 1089, 1093, 1102, 1113, 1134, 1154, 1164, 1173, 1365, 1046, 1056, 1068, 1083, 1086, 1098, 1119, 1143, 1157, 1164, 1175, 1189, 1201, 1368, 1383, 1405, 1412, 1427, 1448, 1462, 1478, 1048, 1059, 1061, 1074, 1097, 1114, 1117, 1129, 1134, 1152, 1164, 1170, 1181, 1194, 1213, 1224, 118, 121, 133, 137, 143, 155, 166, 185, 195, 208, 218, 226, 235, 245, 255, 256, 269, 282, 293, 294, 309, 896, 897, 911, 926, 945, 955, 1324, 1340, 1353, 136, 139, 159, 328, 331, 343, 353, 363, 378, 392, 401, 407, 421, 434, 833, 846, 853, 898, 902, 915, 926, 937, 949, 971, 1044, 1045, 1059, 1075, 1094, 1104, 1109, 1120, 1132, 1178, 1180, 1196, 1207, 1220, 1233, 1247, 1256, 1281, 1318, 1315, 1329, 1342, 1355, 1364, 1370, 1384, 1397, 1407, 1475, 1491, 1495, 1509, 1522, 1545, 119, 136, 147, 160, 168, 182, 195, 325, 330, 344, 355, 369, 383, 396, 409, 421, 432, 449, 463, 478, 491, 494, 519, 536, 554, 567, 577, 590, 841, 893, 907, 920, 935, 1090, 1102, 1108, 1120, 1132, 1324, 1330, 1345, 1360, 1375, 1488, 1504, 1515, 1520, 1532, 1544, 119, 136, 147, 159, 168, 184, 195, 325, 330, 344, 355, 369, 383, 396, 409, 420, 432, 449, 463, 478, 492, 494, 519, 537, 554, 567, 577, 590, 838, 841, 893, 907, 920, 935, 1091, 1103, 1108, 1119, 1132, 1324, 1330, 1345, 1360, 1375, 1488, 1503, 1516, 1520, 1532, 1544, 119, 136, 147, 160, 168, 184, 195, 325, 330, 344, 355, 369, 383, 396, 409, 420, 432, 449, 463, 478, 492, 494, 519, 536, 554, 567, 577, 590, 841, 893, 907, 920, 935, 1091, 1103, 1108, 1120, 1132, 1324, 1330, 1345, 1360, 1375, 1489, 1504, 1512, 1520, 1532, 1544, 119, 136, 147, 160, 168, 184, 195, 325, 330, 344, 355, 369, 383, 396, 409, 420, 432, 449, 463, 478, 492, 494, 519, 537, 554, 567, 577, 590, 841, 893, 907, 920, 935, 1091, 1103, 1108, 1120, 1132, 1324, 1330, 1345, 1360, 1375, 1488, 1504, 1515, 1520, 1532, 1544, 119, 129, 145, 157, 169, 184, 194, 329, 340, 354, 370, 373, 379, 396, 417, 437, 456, 474, 486, 497, 509, 527, 539, 555, 569, 583, 841, 892, 907, 920, 935, 1088, 1103, 1108, 1120, 1132, 1324, 1330, 1345, 1360, 1375, 1504, 1516, 1520, 1532, 1544, 127, 133, 148, 160, 172, 184, 199, 211, 225, 325, 330, 344, 355, 369, 383, 396, 409, 420, 432, 449, 463, 475, 491, 505, 520, 533, 536, 561, 578, 589, 602, 613, 615, 638, 656, 660, 672, 691, 705, 718, 838, 893, 907, 920, 935, 1076, 1091, 1103, 1108, 1120, 1132, 1324, 1330, 1345, 1360, 1375, 1488, 1503, 1515, 1520, 1532, 1544, 127, 133, 148, 160, 172, 184, 199, 211, 225, 325, 330, 344, 355, 369, 383, 396, 409, 420, 432, 449, 463, 475, 505, 512, 520, 536, 545, 561, 578, 591, 591, 615, 625, 638, 655, 660, 672, 691, 704, 718, 838, 893, 907, 920, 935, 1076, 1091, 1103, 1108, 1120, 1132, 1324, 1330, 1345, 1360, 1375, 1488, 1503, 1516, 1520, 1532, 1544, 1181, 1182, 1195, 1204, 1222, 1240, 1256, 1272, 1289, 1289, 1301, 1317, 1323, 1345, 1361, 1374, 1487, 1499, 1512, 1519, 1531, 1545, 1297, 1306, 1328, 1348, 1362, 1374, 1488, 1504, 1516, 1520, 1532, 1544, 1184, 1186, 1199, 1208, 1225, 1244, 1257, 1275, 1289, 1287, 1301, 1317, 1323, 1345, 1361, 1374, 1466, 1474, 1487, 1499, 1513, 1513, 1531, 1544, 407, 408, 424, 440, 469, 489, 501, 518, 524, 541, 561, 579, 583, 592, 606, 621, 629, 633, 648, 664, 678, 694, 717, 728, 742, 757, 758, 773, 783, 804, 827, 835, 851, 865, 881, 908, 923, 938, 938, 953, 980, 996, 1001, 1016, 1025, 1036, 1060, 1069, 1077, 1097, 1113, 1126, 1142, 1143, 1157, 1169], 'top': [2193, 2193, 2188, 2188, 2192, 2188, 2193, 2192, 1923, 1922, 1923, 1923, 1913, 1920, 1918, 1922, 1918, 1918, 1920, 1918, 1918, 1922, 1918, 1922, 1922, 1918, 1885, 1884, 1880, 1885, 1880, 1880, 1884, 1880, 1880, 1885, 1880, 1885, 1885, 1880, 1880, 1884, 1884, 1884, 1884, 1880, 1846, 1842, 1842, 1842, 1846, 1842, 1842, 1845, 1846, 1846, 1842, 1845, 1847, 1846, 1833, 1846, 1842, 1842, 1842, 1842, 1847, 1847, 1842, 1847, 1847, 1847, 1847, 1809, 1813, 1809, 1804, 1804, 1804, 1804, 1813, 1804, 1804, 1804, 1809, 1809, 1809, 1804, 1809, 1809, 1804, 1804, 1804, 1809, 1804, 1771, 1771, 1766, 1766, 1771, 1772, 1766, 1772, 1766, 1771, 1771, 1766, 1795, 1791, 1733, 1729, 1734, 1733, 1734, 1729, 1729, 1729, 1734, 1729, 1729, 1695, 1696, 1696, 1691, 1691, 1691, 1695, 1695, 1691, 1658, 1658, 1653, 1658, 1658, 1653, 1658, 1653, 1657, 1657, 1653, 1687, 1619, 1615, 1615, 1619, 1615, 1615, 1618, 1619, 1620, 1618, 1620, 1615, 1620, 1624, 1624, 1624, 1624, 1624, 1624, 1624, 1624, 1582, 1583, 1577, 1577, 1583, 1583, 1582, 1577, 1583, 1583, 1583, 1580, 1577, 1583, 1582, 1577, 1497, 1496, 1492, 1497, 1496, 1491, 1492, 1492, 1496, 1492, 1492, 1495, 1497, 1492, 1497, 1492, 1497, 1492, 1497, 1492, 1492, 1360, 1359, 1355, 1360, 1361, 1361, 1360, 1359, 1359, 1335, 1330, 1325, 1335, 1330, 1325, 1325, 1325, 1330, 1325, 1328, 1330, 1325, 1325, 1330, 1330, 1328, 1330, 1330, 1325, 1325, 1325, 1325, 1325, 1330, 1330, 1325, 1330, 1330, 1325, 1330, 1325, 1325, 1330, 1330, 1330, 1325, 1325, 1325, 1325, 1328, 1330, 1331, 1330, 1331, 1325, 1325, 1328, 1330, 1331, 1325, 1325, 1330, 1330, 1325, 1325, 1325, 1328, 1272, 1273, 1273, 1272, 1273, 1277, 1273, 1272, 1272, 1272, 1272, 1272, 1273, 1273, 1272, 1273, 1273, 1272, 1272, 1272, 1272, 1272, 1272, 1273, 1273, 1272, 1272, 1273, 1273, 1273, 1272, 1273, 1272, 1273, 1277, 1272, 1273, 1273, 1272, 1272, 1273, 1272, 1273, 1273, 1273, 1272, 1259, 1273, 1273, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1247, 1243, 1243, 1243, 1243, 1243, 1243, 1247, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1243, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1217, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1200, 1213, 1213, 1183, 1184, 1184, 1183, 1183, 1184, 1184, 1184, 1183, 1183, 1183, 1183, 1184, 1184, 1183, 1184, 1184, 1183, 1183, 1183, 1183, 1183, 1183, 1184, 1184, 1183, 1183, 1183, 1184, 1183, 1183, 1184, 1183, 1183, 1188, 1183, 1184, 1184, 1183, 1183, 1184, 1183, 1184, 1183, 1184, 1184, 1170, 1184, 1184, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1158, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1154, 1129, 1124, 1124, 1124, 1125, 1124, 1125, 1124, 1124, 1124, 1124, 1124, 1124, 1124, 1125, 1125, 1124, 1125, 1125, 1124, 1124, 1124, 1124, 1124, 1124, 1124, 1124, 1124, 1125, 1125, 1125, 1125, 1124, 1124, 1124, 1111, 1125, 1124, 1124, 1124, 1125, 1124, 1124, 1125, 1124, 1125, 1125, 1129, 1124, 1125, 1125, 1124, 1124, 1125, 1124, 1125, 1124, 1125, 1124, 1111, 1125, 1124, 1099, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 1095, 10

In [6]:
import cv2
import pytesseract
 
# Mention the installed location of Tesseract-OCR in your system

# Read image from which text needs to be extracted
img = cv2.imread("/home/vimalkumar/Documents/images/Interview/image_1.jpg")
 
# Preprocessing the image starts
 
# Convert the image to gray scale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
 
# Performing OTSU threshold
ret, thresh1 = cv2.threshold(gray, 0, 255, cv2.THRESH_OTSU | cv2.THRESH_BINARY_INV)
 
# Specify structure shape and kernel size.
# Kernel size increases or decreases the area
# of the rectangle to be detected.
# A smaller value like (10, 10) will detect
# each word instead of a sentence.
rect_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (18, 18))
 
# Applying dilation on the threshold image
dilation = cv2.dilate(thresh1, rect_kernel, iterations = 1)
 
# Finding contours
contours, hierarchy = cv2.findContours(dilation, cv2.RETR_EXTERNAL,
                                                 cv2.CHAIN_APPROX_NONE)
 
# Creating a copy of image
im2 = img.copy()
 
# A text file is created and flushed
file = open("recognized.txt", "w+")
file.write("")
file.close()
 
# Looping through the identified contours
# Then rectangular part is cropped and passed on
# to pytesseract for extracting text from it
# Extracted text is then written into the text file
for cnt in contours:
    x, y, w, h = cv2.boundingRect(cnt)
     
    # Drawing a rectangle on copied image
    rect = cv2.rectangle(im2, (x, y), (x + w, y + h), (0, 255, 0), 2)
     
    # Cropping the text block for giving input to OCR
    cropped = im2[y:y + h, x:x + w]
     
    # Open the file in append mode
    file = open("recognized.txt", "a")
     
    # Apply OCR on the cropped image
    text = pytesseract.image_to_string(cropped)
     
    # Appending the text into file
    file.write(text)
    file.write("\n")
     
    # Close the file
    file.close

In [1]:
import cv2
import pytesseract

In [2]:
im = cv2.imread('/home/vimalkumar/Documents/images/Interview/image_1.jpg')

In [12]:
im_ex = pytesseract.image_to_string(im,config = r'--oem 3 --psm 6')

In [13]:
print(im_ex)

Page 1 of 1
Bill-to Customer No.
Prices Including VAT No
Document Date 14. December 2020
Salesperson Niall Gannon
Your Order No. as
Job Location
Cheque No.
Our Order No. ly
Payment Method ON A/C TRA
Goods Collected By
Delivery Instructions:
Unit of VAT
No. Description Qty Measure Unit Price Discount % Identifier Amount
FO27103 FIBERGLASS LADDER 3 STEP 3 EACH 35.00 HIGHC 105.00
FO27104 FIBERGLASS LADDER 4 STEP 3. EACH 41.50 HIGHC 124.50
FO27105 FIBERGLASS LADDER 5 STEP 3 EACH 47.00 HIGHC 141.00
FO27106 FIBERGLASS LADDER 6 STEP 3 EACH 55.00 HIGHC 165.00
LFD66AL ALUMINIUM 2 STEP STOOL 3 EACH 16.00 HIGHC 48.00
LAD430GFA FIBERGLASS EXT LADDER 28STEP 7.6MTR 1 EACH 125.00 HIGHC 125.00
LADS60GFA FIBERGLASS EXT LADDER 36STEP 9.7MTR 1 EACH 150.00 HIGHC 150.00
Total EUR Excl. VAT 858.50
21% VAT 180.29
Total EUR Incl. VAT 1,038.79
Goods remain strictly the property of the Vendor until paid in full

In [11]:
import re
re.findall('\d+\.\d+',im_ex)

['7.6',
 '9.7',
 '35.00',
 '41.50',
 '47.00',
 '55.00',
 '16.00',
 '125.00',
 '150.00',
 '105.00',
 '124.50',
 '141.00',
 '165.00',
 '48.00',
 '125.00',
 '150.00',
 '858.50',
 '180.29',
 '038.79']